name: Add Comment
on: pull_request

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Job fail
        id: job-fail
        run: |
          exit 0 
      - name: Find Comment
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: latest updates on your project

      - uses: haya14busa/action-cond@v1
        id: condval
        if: always() && github.event_name == 'pull_request'
        with:
          cond: ${{ steps.job-fail.outcome == 'success' }}
          if_true: |-
              **The latest updates on your project**
              <table class="tg">
                <thead>
                  <tr>
                    <th > App Name</th>
                    <th> Build Status</th>
                    <th> Build Version</th>
                    <th> Build Commit</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td> ${{env.APP_NAME}} </td>
                    <td> ✅ Ready </td>
                    <td> ${{env.VERSION}} </td>
                    <td> ${{ github.event.pull_request.head.sha }} </td>
                </tbody>
              </table>
          if_false: |-
              **The latest updates on your project**
              <table class="tg">
                <thead>
                  <tr>
                    <th > App Name</th>
                    <th> Build Status</th>
                    <th> Build Version</th>
                    <th> Build Commit</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td> ${{env.APP_NAME}} </td>
                    <td> ❌ Failed </td>
                    <td> ${{env.VERSION}} </td>
                    <td> ${{ github.event.pull_request.head.sha }} </td>
                </tbody>
              </table>

      - name: Create comment
        if: always() && github.event_name == 'pull_request' && steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.condval.outputs.value }}
          reactions: rocket

      - name: Update comment
        if: always() && github.event_name == 'pull_request' && steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.condval.outputs.value }}
          edit-mode: replace
