name: Add Comment
on:
  pull_request:

env:
  VERSION: xxxxx12345-version

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Job fail
        run: |
          exit 1
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This comment was written by a bot!

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This comment was written by a bot! version: ${{ env.VERSION }}
          reactions: rocket

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            New version: ${{ env.VERSION }}
          edit-mode: replace
