name: Github Context Dump
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name
        required: true

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app-another-33333

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
