name: Github Context Dump
on: [push]

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app-another-33333

jobs:
  dump:
    runs-on: ubuntu-latest
    if: "${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'build: update version') && github.event.head_commit.author.name == 'Nitin Kumar' }}"
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
