name: Github Context Dump
on:
  pull_request:
  push:

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app-another-33333

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Set time
        run: echo ::set-env name=WORKFLOW_START_TIME::$(date +%s) 
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      - name: Github context
        run: echo '${{ toJSON(github) }}'
