name: Github Context Dump
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app-another-33333

jobs:
  dump:
    runs-on: windows-latest
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run script
        run: node ./a.js
