name: Github Context Dump
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name
        required: true
      isHotfixRelease:
        description: Is this a hotfix release? (yes/no)
        required: true

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app-another-33333

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Update experimental version of packages
        if: "${{ github.event.inputs.isHotfixRelease != 'yes' }}"
        run: echo "exp version"
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_ACCESS_TOKEN }}
          TAG: experimental-${{ github.event.inputs.tag }}
      - name: Update hotfix version of packages
        if: "${{ github.event.inputs.isHotfixRelease == 'yes' }}"
        run: echo "hotfix version"
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_ACCESS_TOKEN }}
          TAG: hotfix-${{ github.event.inputs.tag }}
      - name: Publish experimental packages
        if: "${{ github.event.inputs.isHotfixRelease != 'yes' }}"
        run: echo "exp publish"
        env:
          TAG: experimental-${{ github.event.inputs.tag }}
      - name: Publish hotfix packages
        if: "${{ github.event.inputs.isHotfixRelease == 'yes' }}"
        run: echo "hotfix publish"
        env:
          TAG: hotfix-${{ github.event.inputs.tag }}
      - name: Github context
        run: echo '${{ toJSON(github) }}'
      - name: Update Version
        run: |
          echo "VERSI='test'" >> $GITHUB_ENV
          echo "VERSION='test'" >> $GITHUB_ENV
          echo $VERSION
          echo $VERSI
