name: Github Context Dump
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name
        required: true
      isHotfixRelease:
        description: Is this a hotfix release? (yes/no)
        required: true

env:
  VERSION: xxxxx12345-new-version
  APP_NAME: universe-app-another-33333

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Sets env vars for experimental release
        run: |
          echo "TAG=experimental-${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        if:  "${{ github.event.inputs.isHotfixRelease == 'no' }}"
      - name: Sets env vars for hotfix release
        run: |
          echo "TAG=hotfix-${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        if: "${{ github.event.inputs.isHotfixRelease == 'yes' }}"
      - name: Github context
        run: echo '${{ toJSON(github) }}'
