name: Release

on:
  push:
    branches: [master]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  HOME: /actions-runner/_work

jobs:
  release:
    name: Release
    runs-on: self-hosted
    timeout-minutes: 45
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node v14.19
        uses: actions/setup-node@v2
        with:
          node-version: 14.19
      - name: Create Release Pull Request & Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "build(universe): update version"
          title: "build(universe): update version"
