name: Comment changeset guidelines

on:
  issue_comment:
    types:
      - created

jobs:
  run-on-comment:
    name: Comment changeset guidelines
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
