name: Comment changeset guidelines
on:
  issue_comment:
    types:
      - created
env:
  APP_NAME: my-app
  COMMENT_BODY: Your devstack deployment is available at https://${{ env.APP_NAME }}-pr-1746.dev.razorpay.in

jobs:
  run-on-comment:
    name: Comment changeset guidelines
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
