name: Comment changeset guidelines
on:
  issue_comment:
    types:
      - created
env:
  APP_NAME: my-app
  COMMENT_BODY: Your devstack deployment is available at https://pr-${{ github.event.issue.number }}.in

jobs:
  run-on-comment:
    name: Comment changeset guidelines
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
