name: Comment changeset guidelines

on:
  issue_comment:
    types:
      - created

jobs:
  comment-changeset-guidelines:
    name: Comment changeset guidelines
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Github context
        run: echo '${{ toJSON(github) }}'
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: Click here to learn what changesets are
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            "[Click here to read our changeset guidelines](https://github.com/razorpay/frontend-universe/blob/master/CONTRIBUTING.md#-writing-a-changeset)"
